### ISSUE TITLE
npm ERR! code EBADPLATFORM

### ISSUE THREAD

**Issue by maifeeulasad** [DEVLOPRR/vite-react-neutralino#1]
Full log:
```
vite-react-neutralino>npm i
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!
npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm ERR! notsup Valid OS:    darwin
npm ERR! notsup Valid Arch:  any
npm ERR! notsup Actual OS:   win32
npm ERR! notsup Actual Arch: x64
```
Deleting `package-lock.json` and running this command again, _resolved_(**hopefully**) this issue.

**Comment by pegvin** [comment]
Hi there, i removed the `package-lock.json` From the repository but it seems like you are using old NPM version maybe 5 or 6, i suggest you to update your npm version, also i updated the repository, please can you try again?

**Comment by maifeeulasad** [comment]
@pegvin it's fine now.

But I was thinking should we delete `package-lock.json`?

Ref: https://stackoverflow.com/q/54124033/10305444

**Comment by pegvin** [comment]
i will add the `package-lock.json` but seems like it messes with older npm versions.
